### ISSUE TITLE
About to setup Lab 2.0

### ISSUE THREAD

**Issue by ghost** [vpj/python_autocomplete#1]
Hi,

Thanks for sharing a source code of python-auto-completion. 

I would like to run it, but I could not be to figure out "how can I setup Lab 2.0 in windows?" I did not find any command to install Lab 2.0. 

Similarly, command "ln -s ~/repo/lab your_project/lab" is mentioned in [lab 2.0](https://github.com/vpj/lab) project, but it can be worked in Linux environment.

Kindly let me know about how can I set up Lab 2.0 in Windows, in order to run  python-auto-completion project.

**Comment by vpj** [comment]
Hey I'm extremely sorry for the loooong delay.

I updated the code to use the latest version of lab. Hope it works now for you.
